export default [
    {
        value: 'require',
        label: '必填',
        message: '请输入{file_name}',
        params: false,
        tip: '',
    },
    {
        value: 'in',
        label: '在某个范围',
        message: '请选择正确的{file_name}',
        params: true,
        tip: '如：1,2,3',
    },
    {
        value: 'confirm',
        label: '与某个字段值相等',
        message: '{file_name}必须与：',
        params: true,
        tip: '如：password',
    },
    {
        value: 'unique',
        label: '字段的值唯一',
        message: '{file_name}已存在',
        params: true,
        tip: '如：AdminUser，代表AdminUser表唯一',
    },
    {
        value: 'mobile',
        label: '有效的手机',
        message: '请输入正确的{file_name}',
        params: false,
        tip: '',
    },
    {
        value: 'idCard',
        label: '身份证',
        message: '请输入正确的身份证号',
        params: false,
        tip: '',
    },
    {
        value: 'url',
        label: 'URL地址',
        message: '{file_name}只能是有效的URL地址',
        params: false,
        tip: '',
    },
    {
        value: 'between',
        label: '某个区间',
        message: '{file_name}只能是：',
        params: true,
        tip: '如：1,10',
    },
    {
        value: 'max',
        label: '最大长度',
        message: '{file_name}最大长度为：',
        params: true,
        tip: '如：10',
    },
    {
        value: 'min',
        label: '最小长度',
        message: '{file_name}最小长度为：',
        params: true,
        tip: '如：10',
    },
    {
        value: 'length',
        label: '长度',
        message: '{file_name}长度必须是：',
        params: true,
        tip: '如：1,10；代表1到10位，如：4；代表长度位4',
    },
    {
        value: 'egt',
        label: '大于等于',
        message: '{file_name}必须大于等于',
        params: true,
        tip: '如：100',
    },
    {
        value: 'elt',
        label: '小于等于',
        message: '{file_name}必须小于等于',
        params: true,
        tip: '如：100',
    },
    {
        value: 'number',
        label: '数字',
        message: '{file_name}必须是数字',
        params: false,
        tip: '',
    },
    {
        value: 'integer',
        label: '整数',
        message: '{file_name}必须是整数',
        params: false,
        tip: '',
    },
    {
        value: 'float',
        label: '浮点数',
        message: '{file_name}必须是浮点数',
        params: false,
        tip: '',
    },
    {
        value: 'boolean',
        label: '布尔值',
        message: '请选择{file_name}',
        params: false,
        tip: '',
    },
    {
        value: 'email',
        label: '邮箱',
        message: '请填写正确的邮箱',
        params: false,
        tip: '',
    },
    {
        value: 'array',
        label: '数组',
        message: '请选择{file_name}',
        params: false,
        tip: '',
    },
    // {
    //     value: 'string',
    //     label: '字符串',
    //     message: '{file_name}必须是字符串',
    // },
    // {
    //     value: 'accepted',
    //     label: 'yes/no或1',
    //     message: '请选择{file_name}',
    // },
    {
        value: 'date',
        label: '有效日期',
        message: '{file_name}请选择正确的日期',
        params: false,
        tip: '',
    },
    {
        value: 'alpha',
        label: '纯字母',
        message: '{file_name}必须是字母',
        params: false,
        tip: '',
    },
    {
        value: 'alphaNum',
        label: '字母和数字',
        message: '{file_name}必须是字母和数字',
        params: false,
        tip: '',
    },
    // {
    //     value: 'alphaDash',
    //     label: '字母数字下划线破折号',
    //     message: '{file_name}必须是字母数字下划线_破折号-',
    // },
    // {
    //     value: 'chs',
    //     label: '汉字',
    //     message: '{file_name}必须是汉字',
    // },
    // {
    //     value: 'chsAlpha',
    //     label: '汉字加字母',
    //     message: '{file_name}必须是汉字、字母',
    // },
    // {
    //     value: 'chsAlphaNum',
    //     label: '汉字字母数字',
    //     message: '{file_name}必须是汉字、字母、数字',
    // },
    // {
    //     value: 'cntrl',
    //     label: '换行、缩进、空格',
    //     message: '{file_name}只能是换行、缩进、空格',
    // },
    // {
    //     value: 'graph',
    //     label: '可打印字符（空格除外）',
    //     message: '{file_name}只能是可打印字符（空格除外）',
    // },
    // {
    //     value: 'print',
    //     label: '可打印字符（包括空格）',
    //     message: '{file_name}只能是可打印字符（包括空格）',
    // },
    {
        value: 'lower',
        label: '小写字符',
        message: '{file_name}只能是小写字符',
        params: false,
        tip: '',
    },
    {
        value: 'upper',
        label: '大写字符',
        message: '{file_name}只能是大写字符',
        params: false,
        tip: '',
    },
    {
        value: 'xdigit',
        label: '十六进制字符串',
        message: '{file_name}只能是十六进制字符串',
        params: false,
        tip: '',
    },
    {
        value: 'activeUrl',
        label: '有效的域名或者IP',
        message: '{file_name}只能是有效的域名或者IP',
        params: false,
        tip: '',
    },

    {
        value: 'ip',
        label: 'IP地址',
        message: '{file_name}只能是有效的IP地址',
        params: false,
        tip: '',
    },
    // {
    //     value: 'dateFormat',
    //     label: '指定格式的日期',
    //     message: '{file_name}日期格式错误，必须为：',
    // },

    {
        value: 'macAddr',
        label: 'MAC地址',
        message: 'MAC地址格式错误',
        params: false,
        tip: '',
    },
    {
        value: 'zip',
        label: '邮政编码',
        message: '邮政编码格式错误',
        params: false,
        tip: '',
    },

    {
        value: 'notIn',
        label: '不在某个范围',
        message: '{file_name}不能选择：',
        params: true,
        tip: '如：1,2,3',
    },

    {
        value: 'notBetween',
        label: '不在某个区间',
        message: '{file_name}不能是：',
        params: true,
        tip: '如：1,10',
    },


    {
        value: 'after',
        label: '某个日期之后',
        message: '{file_name}必须大于：',
        params: true,
        tip: '如：2016-3-18',
    },
    {
        value: 'before',
        label: '某个日期之前',
        message: '{file_name}必须小于：',
        params: true,
        tip: '如：2016-3-18',
    },
    {
        value: 'expire',
        label: '日期之间',
        message: '{file_name}必须在：',
        params: true,
        tip: '如：2016-2-1,2016-10-01',
    },

    {
        value: 'different',
        label: '与某个字段值不相等',
        message: '{file_name}必须与：',
        params: true,
        tip: '如：password',
    },
    {
        value: 'eq',
        label: '等于',
        message: '{file_name}必须等于',
        params: true,
        tip: '如：100',
    },

    {
        value: 'lt',
        label: '小于',
        message: '{file_name}必须小于',
        params: true,
        tip: '如：100',
    },

    {
        value: 'requireIf',
        label: '当某字段等于xx的时候必须',
        message: '请输入{file_name}',
        params: true,
        tip: '如：account,1；代表account等于1的时候必须',
    },
    {
        value: 'requireWith',
        label: '当某字段有值的时候必须',
        message: '请输入{file_name}',
        params: true,
        tip: '如：account；代表account字段有值的是必填',
    },
    {
        value: 'requireWithout',
        label: '当某字段没有值的时候必须',
        message: '{file_name}必须为空',
        params: true,
        tip: '如：account；代表account字段没有值的是必填',
    },
];
